[package]
name = "projet"
version = "0.1.0"
authors = ["R.Chavignat <r.chavignat@gmail.com>"]

[dependencies]
docopt = "0.6.86"
docopt_macros = "0.6.87"
image = "0.10.4"
nalgebra = "0.10.1"
rustc-serialize = "0.3.22"
